### ISSUE TITLE
Links on the website are broken

### ISSUE THREAD

**Issue by dalejefferson-rnf** [voltpkg/volt#14]
- Features
- Docs
- Contribute
- Community
- Twitter
- Facebook
- Get Started

And the search does not seem to work, the whole site looks to be broken.

![image](https://user-images.githubusercontent.com/46318618/128686001-4d7f58ce-b636-4608-9d80-9c5a738cd899.png)

**Comment by XtremeDevX** [comment]
@dalejefferson-rnf I'm sorry the website didn't work for you, but this behavior is expected - I'm currently focusing on developing the product, not the website just yet. Since I don't have a "team" to work on this, if anyone would like to volunteer to developing the website, contributions are more than welcome and we have our website hosted here https://github.com/voltpkg/website. 

Also we're having a website discussion on #website at the [official discord server](https://discord.gg/fPBn2NTf), so feel free to join. Thanks!

**Comment by dalejefferson-rnf** [comment]
Maybe remove the link from the Github project page until the website is functional? I'm interested in the project do you have any documentation on how to use it, or is the project in very early stages?

**Comment by XtremeDevX** [comment]
😁 The project is still in a really early stage, but the main mechanisms that are going to make it much faster have already been put in place. Right now I'm in the middle of a large refactor (I'm following advice from an expert and changing the code) so the code will be broken for a bit.
