### ISSUE TITLE
Any relation to Volta?

### ISSUE THREAD

**Issue by kjvalencik** [voltpkg/volt#16]
Hi! This looks like a really cool project! The performance numbers are impressive.

Quick question, does this project have any relation to [Volta](https://volta.sh), the Node version / tool manager?

**Comment by XtremeDevX** [comment]
😁 thanks for your kind words! No, Volt is completely unrelated to Volta although it's by pure coincidence that they're both written in Rust 🤣

**Comment by dherman** [comment]
This looks like a cool project! Im always excited to see innovation in the space of package managers, and (as the original creator of Volta!) I’m a big believer in Rust’s ability to push the envelope in performance and usability of JS tools. Can’t wait to see how this project moves JS package management forward!

@XtremeDevX I’m a little concerned about the possibility of confusion with Volta, especially given the proximity of the toolchain management and package management spaces. Since this project is still pretty young  (Volta itself went through a few rebrands in its early years before settling on its final name), do you think you might be open to considering alternative names to avoid confusion?

**Comment by XtremeDevX** [comment]
@dherman Absolute pleasure to connect with you!. 

Well, yes I'm still open to considering changes to the name, though, I do personally feel the name `Volt` brings out a lot about what Volt does and its objectives very well. 

That being said, I'm still completely open to checking out alternative names for Volt 😋 !

**Comment by dherman** [comment]
Thanks so much for being open to it, @XtremeDevX! Let me know if there's anything I can do to help. I'd also love to connect some time to learn about your goals for the project and see if there are any interesting collaboration opportunities for our projects. /cc @CharlesPierce

**Comment by XtremeDevX** [comment]
😝 Will have to start thinking about alternate names and see if anything could possibly replace Volt. 

Yes, would absolutely love to connect 😁 `xtremedevx#0007` on Discord or `@XtremeDevX` on Twitter!
